version: '1.0'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env:
      - PORT=5000 # Exemplo de variável de ambiente para a porta do backend
    ports:
      - 5000:5000 # Mapeamento da porta do host para a porta do container
