apiVersion: batch/v1
kind: CronJob
metadata:
  name: scale-down-cronjob
spec:
  schedule: "0 22 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scale-down
            image: google/cloud-sdk
            command: ["/bin/bash", "/path/to/your/scale_down.sh"]
          restartPolicy: OnFailure
